# -*- coding: utf-8 -*-
"""ejercicios1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mc7pfLDAfscY1wOh251thaHoPExxQGrW

Repaso a Python y tema nuevo Vectores y matrices

Muestre por consola el mundo es maravilloso aun en estos momentos tan difíciles.
"""

hi_world="El mundo es maravilloso aun en estos momentos tan difíciles"

print(hi_world)

"""Imprima el resultado de las cinco operaciones matemática suma, resta, multiplicación, 
división.
"""

a=20
b=80

c=a+b
d=a-b
e=a*b
f=a/b

print(c)

print(d)

print(e)

print(f)

"""Diseñar un algoritmo que promedie 3 notas, si este es mayor o igual a 3.8, aprobó de lo 
contrario no aprobó,

"""

nota1 = float(input("Ingrese la nota 1: "))
nota2 = float(input("Ingrese la nota 2: "))
nota3 = float(input("Ingrese la nota 3: "))

promedio = (nota1 + nota2 + nota3) / 3

if promedio >= 3.8:
    print("Felicitaciones ha Aprobado")
    print("su promedio es",promedio)
else:
    print("El resultado del promedio fue insufueciente por lo tanto no aprobó")

    print("su promedio es",promedio)

"""Le han contrato a usted para diseñar un programa de relaciones humanas que contenga los 
siguientes puntos:

• Prueba practica: oscila entre 40.

• Prueba psicológica:30 puntos

• Prueba técnica:20

• Hoja de vida:10

Si la suma de los puntajes da mas de 70 puntos el postulante será contratado, de lo contrario 
aplazado.

"""

# Pedir al usuario que ingrese los puntajes de cada prueba
practica = int(input("Ingrese el puntaje de la prueba práctica (de 0 a 40): "))
psicologica = int(input("Ingrese el puntaje de la prueba psicológica (de 0 a 30): "))
tecnica = int(input("Ingrese el puntaje de la prueba técnica (de 0 a 20): "))
hoja_vida = int(input("Ingrese el puntaje de la hoja de vida (de 0 a 10): "))

# Calcular la suma de los puntajes
suma_puntajes = practica + psicologica + tecnica + hoja_vida

# Verificar si la suma de los puntajes es mayor o igual a 70 y mostrar el resultado
if suma_puntajes >= 70:
    print("El postulante ha sido contratado")
else:
    print("El puntaje del postulado ha sido ",suma_puntajes," Por lo tanto el postulante ha sido aplazado")

"""Concatenar su nombre y apellido

"""

nombre1= ' Johan'
nombre2= ' Santiago'
apellido1= ' Villanueva'
apellido2= ' Roa'

Nombre_concatenado = nombre1+ nombre2+ apellido1+ apellido2
print(nombre1)
print(nombre2)
print(apellido1)
print(apellido2)

print(' su nombre completo es')
print(Nombre_concatenado)

"""Convertir de minúsculas a mayúsculas"""

texto= 'johan'

print(texto)
TEXTO=texto.upper()
print(TEXTO)

"""Convertir a mayúsculas la primera letra

"""

texto= 'santiago'
print(texto)

Texto= texto.capitalize()
print(Texto)

""" Centrar el texto: “La vida es la prioridad del ser humano”"""

Texto = 'La vida es la prioridad del ser humano'

print(Texto)

centrado = Texto.center( 50, ' ')

print(centrado)

"""Diseñe un algoritmo que muestre los números en del 1 al 10"""

for i in range(1, 11):
    print(i)

"""Leer números enteros de teclado, hasta que el usuario ingrese el 1.5. Finalmente, mostrar 
la sumatoria de todos los números ingresados
"""

suma=0

while True:
      num = input("ingresa el numero que decees")
      if num == '1.5':
          break
      else:
          suma += int(num)

print("la sumatoria de los numeroes es",suma)